name: "Submit to Web Store"
on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to publish (chrome/firefox/edge/all)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - name: Build and Package for Chrome
        if: ${{ github.event.inputs.browser == 'chrome' || github.event.inputs.browser == 'all' }}
        run: |
          pnpm build:chrome
          pnpm package:chrome
      - name: Upload Chrome Artifact
        if: ${{ github.event.inputs.browser == 'chrome' || github.event.inputs.browser == 'all' }}
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: build/chrome-mv3-prod
      - name: Publish to Chrome Web Store
        if: ${{ github.event.inputs.browser == 'chrome' || github.event.inputs.browser == 'all' }}
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
      - name: Build and Package for Firefox
        if: ${{ github.event.inputs.browser == 'firefox' || github.event.inputs.browser == 'all' }}
        run: |
          pnpm build:firefox
          pnpm package:firefox
      - name: Upload Firefox Artifact
        if: ${{ github.event.inputs.browser == 'firefox' || github.event.inputs.browser == 'all' }}
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: build/firefox-mv3-prod
      - name: Publish to Firefox Add-ons
        if: ${{ github.event.inputs.browser == 'firefox' || github.event.inputs.browser == 'all' }}
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          firefox-file: build/firefox-mv3-prod.zip
      - name: Build and Package for Edge
        if: ${{ github.event.inputs.browser == 'edge' || github.event.inputs.browser == 'all' }}
        run: |
          pnpm build:edge
          pnpm package:edge
      - name: Upload Edge Artifact
        if: ${{ github.event.inputs.browser == 'edge' || github.event.inputs.browser == 'all' }}
        uses: actions/upload-artifact@v4
        with:
          name: edge-extension
          path: build/edge-mv3-prod
      - name: Publish to Edge Add-ons
        if: ${{ github.event.inputs.browser == 'edge' || github.event.inputs.browser == 'all' }}
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          edge-file: build/edge-mv3-prod.zip
